### ISSUE TITLE
Agregar un mensaje que describa a la comunidad en el home page.

### ISSUE THREAD

**Issue by afk-mario** [indi-es/indi-es.com#6]
Actualmente no tenemos ningún texto explicando que es INDI·ES puede ser confuso para quien no nos conozca.

Propuesta de mensaje:

```
Bienvenido a INDI·ES, somos una comunidad de desarrollo de videojuegos en español, ¡tod@s son bienvenidos!
```
Tal vez valga la pena después hacer una página de `Acerca de`

![image](https://user-images.githubusercontent.com/1025751/134214214-31f9c1d3-797e-4ec7-9095-85d80f4ae9f6.png)

**Comment by afk-mario** [comment]
Relevant file https://github.com/indi-es/indi-es.com/blob/main/views/home/index.js

**Comment by Ucamo** [comment]
Se envió un Pull request al respecto en https://github.com/indi-es/indi-es.com/pull/7

**Comment by afk-mario** [comment]
closed #7
